<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1 (Total recall)

| **Term**   | **Brief description**                                                                               |
|------------|-----------------------------------------------------------------------------------------------------|
| Subsetting | Selecting part of the data in a list or an array.                                                   |
| Indexing   | Selecting 1 element of a list or an array.                                                          |
| Slicing    | Selecting a range of elements.                                                                      |
| Masking    | Using a conditional expression to select elements of an array that satisfy the condition. |

# Exercise 2 (Show me the 'odd' letters)

In [3]:
import numpy as np

In [4]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"], [5, "E"], [7, "G"], [6, "F"], [8, "H"], [10, "J"], [9, "I"]])

In [9]:
# Obtain a slice of np_array_2d containing the first element of each array.
# NumPy arrays can only store 1 data type. The integers will be promoted to a string during array creation,
# according to promotion rules (https://numpy.org/doc/2.1/reference/arrays.promotion.html). Therefore, we
# need to cast the array to the data type int.
numbers = np_array_2d[:, 0].astype(int)

In [10]:
# Create a mask that returns True for odd numbers, and False otherwise.
odd_mask = numbers % 2 == 1

In [11]:
# Mask np_array_2d and print the associated letter of every element with an odd number.
print(np_array_2d[odd_mask][:, 1])

['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [106]:
data = [[66, 50, 57, -1, -1], [92, -1, 88, -1, -1], [75, -1, -1, 76, -1], [-1, 51, 87, -1, -1], [71, -1, 67, -1, 69]]

In [107]:
np_data = np.array(data)

In [108]:
# Create masks for numbers below, above and equal to 50.
below_50_mask = np_data < 50
above_50_mask = np_data > 50
equal_50_mask = np_data == 50

In [109]:
np_data[below_50_mask] = -1
np_data[above_50_mask] = 1
np_data[equal_50_mask] = 0

In [110]:
print(np_data)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
